[package]
edition = "2021"
name = "desktop"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
imageproc = "0.22"
minifb = "0.20"
rand = "0.8.4"
rusttype = "0.9.2"
